export type Json = string | number | boolean | null | { [key:string]: Json | undefined } | Json[];
export type Database = { skillswipe: { Tables: {
  profiles:{Row:{id:string;user_id:string|null;full_name:string;headline:string;avatar_url:string|null;company_name:string|null;profile_slug:string;visibility:"private"|"link_only"|"public";created_at:string;updated_at:string};Insert:{id?:string;user_id?:string|null;full_name:string;headline?:string;avatar_url?:string|null;company_name?:string|null;profile_slug:string;visibility?:"private"|"link_only"|"public";created_at?:string;updated_at?:string};Update:Partial<Database["skillswipe"]["Tables"]["profiles"]["Insert"]>};
  skill_domains:{Row:{id:string;name:string;description:string;icon:string;sort_order:number};Insert:{id?:string;name:string;description?:string;icon:string;sort_order?:number};Update:Partial<Database["skillswipe"]["Tables"]["skill_domains"]["Insert"]>};
  skill_claims:{Row:{id:string;skill_domain_id:string;claim_text:string;context_tags:Json;behavioural_chips:Json;active:boolean;sort_order:number};Insert:{id?:string;skill_domain_id:string;claim_text:string;context_tags?:Json;behavioural_chips?:Json;active?:boolean;sort_order?:number};Update:Partial<Database["skillswipe"]["Tables"]["skill_claims"]["Insert"]>};
  invitations:{Row:{id:string;profile_id:string;token_hash:string;inviter_message:string|null;invited_email:string|null;status:"created"|"opened"|"completed"|"expired";expires_at:string;created_at:string};Insert:never;Update:never};
  reviewers:{Row:{id:string;invitation_id:string|null;profile_id:string;display_name:string|null;email:string|null;relationship_type:Relationship;consent_to_store:boolean;created_at:string};Insert:never;Update:never};
  skill_signals:{Row:{id:string;profile_id:string;reviewer_id:string;skill_claim_id:string;response_type:Response;relationship_type:Relationship;context_tag:string|null;selected_behaviours:Json;evidence_text:string|null;show_evidence_publicly:boolean;owner_approved_publicly:boolean;evidence_level:"knows"|"knows_how"|"shows_how"|"does";created_at:string};Insert:never;Update:{show_evidence_publicly?:boolean;owner_approved_publicly?:boolean}};
  claim_confidence_snapshots:{Row:{id:string;profile_id:string;skill_claim_id:string;confidence_score:number;contributor_count:number;independent_relationship_count:number;recognised_count:number;seen_in_practice_count:number;would_call_count:number;public_status:"building_evidence"|"validated";calculated_at:string};Insert:never;Update:never};
  profile_share_cards:{Row:{id:string;profile_id:string;generated_title:string;card_data:Json;generated_at:string};Insert:{id?:string;profile_id:string;generated_title:string;card_data:Json;generated_at?:string};Update:never};
}; Views: Record<string,never>; Functions: Record<string,never>; Enums: Record<string,never>; CompositeTypes: Record<string,never> } };
type Relationship="client"|"direct_manager"|"direct_project_peer"|"cross_functional_colleague"|"mentor"|"community_contact"; type Response="not_seen"|"recognised"|"seen_in_practice"|"would_call"|"skipped";
