do $$ declare d uuid; begin
  insert into skillswipe.skill_domains(name,description,icon,sort_order) values
  ('Account Management','Trust and progress in complex client relationships','handshake',1),('Leadership','Clarity, ownership and sound decisions','compass',2),('Communication','Shared understanding that moves people','messages-square',3),('Problem Solving','Pragmatic thinking through ambiguity','puzzle',4),('Execution','Focused momentum from idea to result','zap',5) on conflict do nothing;
  select id into d from skillswipe.skill_domains where name='Account Management'; insert into skillswipe.skill_claims(skill_domain_id,claim_text,context_tags,behavioural_chips,sort_order) values
  (d,'Builds trust when client relationships are under pressure','["Client escalation","Renewal"]','["Names the real tension","Stays calm under pressure","Creates a credible next step","Balances both sides"]',1),(d,'Identifies the real issue behind a client objection','["Discovery","Objection"]','["Asks precise questions","Separates symptom from cause","Tests assumptions"]',2),(d,'Aligns internal and client stakeholders','["Stakeholder alignment"]','["Surfaces trade-offs","Creates shared language","Clarifies ownership"]',3),(d,'Moves a complex account decision forward','["Decision","Renewal"]','["Maps the decision","Removes blockers","Creates momentum"]',4),(d,'Turns customer feedback into an actionable plan','["Feedback","Planning"]','["Synthesises input","Prioritises needs","Closes the loop"]',5) on conflict do nothing;
  select id into d from skillswipe.skill_domains where name='Leadership'; insert into skillswipe.skill_claims(skill_domain_id,claim_text,context_tags,behavioural_chips,sort_order) select d,x.claim,'[]'::jsonb,'["Creates clarity","Builds ownership","Maintains trust"]'::jsonb,x.n from (values ('Brings calm and clarity during uncertainty',1),('Creates ownership without relying on hierarchy',2),('Makes difficult decisions with incomplete information',3),('Gives direct feedback while preserving trust',4),('Keeps a team aligned around a shared outcome',5)) x(claim,n) on conflict do nothing;
  select id into d from skillswipe.skill_domains where name='Communication'; insert into skillswipe.skill_claims(skill_domain_id,claim_text,context_tags,behavioural_chips,sort_order) select d,x.claim,'[]'::jsonb,'["Listens carefully","Creates shared understanding","Moves conversation forward"]'::jsonb,x.n from (values ('Makes complex subjects easy to understand',1),('Asks questions that reveal what matters',2),('Adapts communication to senior stakeholders',3),('Frames a compelling case for action',4),('Handles disagreement constructively',5)) x(claim,n) on conflict do nothing;
  select id into d from skillswipe.skill_domains where name='Problem Solving'; insert into skillswipe.skill_claims(skill_domain_id,claim_text,context_tags,behavioural_chips,sort_order) select d,x.claim,'[]'::jsonb,'["Finds the signal","Balances trade-offs","Makes it actionable"]'::jsonb,x.n from (values ('Turns ambiguity into a clear problem definition',1),('Sees patterns others miss',2),('Chooses pragmatic solutions over unnecessary complexity',3),('Connects technical and commercial considerations',4),('Anticipates risks before they become expensive',5)) x(claim,n) on conflict do nothing;
  select id into d from skillswipe.skill_domains where name='Execution'; insert into skillswipe.skill_claims(skill_domain_id,claim_text,context_tags,behavioural_chips,sort_order) select d,x.claim,'[]'::jsonb,'["Creates momentum","Prioritises clearly","Follows through"]'::jsonb,x.n from (values ('Turns a vague idea into a workable plan',1),('Creates momentum across multiple stakeholders',2),('Prioritises what matters under pressure',3),('Follows through reliably',4),('Improves a process without waiting to be asked',5)) x(claim,n) on conflict do nothing;
end $$;

do $$ declare p uuid:=gen_random_uuid(); i uuid:=gen_random_uuid(); r uuid; c uuid; rel skillswipe.relationship_type; resp skillswipe.response_type; n int; begin
insert into skillswipe.profiles(id,full_name,headline,company_name,profile_slug,visibility) values(p,'Noor van Dijk','Customer strategy & commercial operations','Northstar Labs','noor-van-dijk','public');
insert into skillswipe.invitations(id,profile_id,token_hash,status) values(i,p,encode(digest('demo-noor','sha256'),'hex'),'completed');
for n in 1..12 loop rel:=(array['client','direct_manager','direct_project_peer','cross_functional_colleague','mentor','community_contact']::skillswipe.relationship_type[])[1+((n-1)%6)]; resp:=(array['would_call','seen_in_practice','recognised']::skillswipe.response_type[])[1+((n-1)%3)]; select sc.id into c from skillswipe.skill_claims sc join skillswipe.skill_domains sd on sd.id=sc.skill_domain_id where sd.name in ('Account Management','Leadership','Communication') order by sd.sort_order,sc.sort_order offset ((n-1)%10) limit 1; insert into skillswipe.reviewers(invitation_id,profile_id,display_name,relationship_type,consent_to_store) values(i,p,'Demo contributor '||n,rel,true) returning id into r; insert into skillswipe.skill_signals(profile_id,reviewer_id,skill_claim_id,response_type,relationship_type,selected_behaviours,evidence_text,show_evidence_publicly,owner_approved_publicly,evidence_level,created_at) values(p,r,c,resp,rel,'["Creates clarity"]',case when n<=4 then (array['Noor reset a tense renewal by naming the real concern and giving both teams a plan.','When priorities changed overnight, Noor created clarity without pretending to know everything.','Her questions helped the customer say what was really at stake.','Noor made the next step feel both calm and credible.'])[n] end,n<=4,n<=3,skillswipe.map_evidence_level(resp,rel),now()-(n||' days')::interval); end loop;
insert into skillswipe.claim_confidence_snapshots(profile_id,skill_claim_id,confidence_score,contributor_count,independent_relationship_count,recognised_count,seen_in_practice_count,would_call_count,public_status) select p,skill_claim_id,case when count(*)>=3 then 74 else 42 end,count(*),count(distinct relationship_type),count(*) filter(where response_type='recognised'),count(*) filter(where response_type='seen_in_practice'),count(*) filter(where response_type='would_call'),case when count(*)>=3 and count(distinct relationship_type)>=2 then 'validated'::skillswipe.public_status else 'building_evidence'::skillswipe.public_status end from skillswipe.skill_signals where profile_id=p group by skill_claim_id;
end $$;
