create schema if not exists skillswipe;
create extension if not exists pgcrypto;

create type skillswipe.profile_visibility as enum ('private','link_only','public');
create type skillswipe.invitation_status as enum ('created','opened','completed','expired');
create type skillswipe.relationship_type as enum ('client','direct_manager','direct_project_peer','cross_functional_colleague','mentor','community_contact');
create type skillswipe.response_type as enum ('not_seen','recognised','seen_in_practice','would_call','skipped');
create type skillswipe.evidence_level as enum ('knows','knows_how','shows_how','does');
create type skillswipe.public_status as enum ('building_evidence','validated');

create table skillswipe.profiles (
  id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null,
  full_name text not null check (length(trim(full_name)) between 2 and 100), headline text not null default '', avatar_url text,
  company_name text, profile_slug text not null unique check (profile_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  visibility skillswipe.profile_visibility not null default 'private', created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table skillswipe.skill_domains (id uuid primary key default gen_random_uuid(), name text not null unique, description text not null default '', icon text not null, sort_order integer not null default 0);
create table skillswipe.skill_claims (id uuid primary key default gen_random_uuid(), skill_domain_id uuid not null references skillswipe.skill_domains(id) on delete cascade, claim_text text not null, context_tags jsonb not null default '[]' check (jsonb_typeof(context_tags)='array'), behavioural_chips jsonb not null default '[]' check (jsonb_typeof(behavioural_chips)='array'), active boolean not null default true, sort_order integer not null default 0, unique(skill_domain_id,claim_text));
create table skillswipe.invitations (id uuid primary key default gen_random_uuid(), profile_id uuid not null references skillswipe.profiles(id) on delete cascade, token_hash text not null unique, inviter_message text, invited_email text, status skillswipe.invitation_status not null default 'created', expires_at timestamptz not null default now()+interval '30 days', created_at timestamptz not null default now());
create table skillswipe.reviewers (id uuid primary key default gen_random_uuid(), invitation_id uuid references skillswipe.invitations(id) on delete set null, profile_id uuid not null references skillswipe.profiles(id) on delete cascade, display_name text, email text, relationship_type skillswipe.relationship_type not null, consent_to_store boolean not null check (consent_to_store), created_at timestamptz not null default now());
create table skillswipe.skill_signals (id uuid primary key default gen_random_uuid(), profile_id uuid not null references skillswipe.profiles(id) on delete cascade, reviewer_id uuid not null references skillswipe.reviewers(id) on delete restrict, skill_claim_id uuid not null references skillswipe.skill_claims(id) on delete restrict, response_type skillswipe.response_type not null, relationship_type skillswipe.relationship_type not null, context_tag text, selected_behaviours jsonb not null default '[]' check (jsonb_typeof(selected_behaviours)='array'), evidence_text text check (char_length(evidence_text)<=180), show_evidence_publicly boolean not null default false, owner_approved_publicly boolean not null default false, evidence_level skillswipe.evidence_level not null, created_at timestamptz not null default now(), unique(reviewer_id,skill_claim_id));
create table skillswipe.claim_confidence_snapshots (id uuid primary key default gen_random_uuid(), profile_id uuid not null references skillswipe.profiles(id) on delete cascade, skill_claim_id uuid not null references skillswipe.skill_claims(id) on delete cascade, confidence_score numeric(5,2) not null check (confidence_score between 0 and 100), contributor_count integer not null check (contributor_count>=0), independent_relationship_count integer not null check (independent_relationship_count>=0), recognised_count integer not null default 0, seen_in_practice_count integer not null default 0, would_call_count integer not null default 0, public_status skillswipe.public_status not null, calculated_at timestamptz not null default now());
create table skillswipe.profile_share_cards (id uuid primary key default gen_random_uuid(), profile_id uuid not null references skillswipe.profiles(id) on delete cascade, generated_title text not null, card_data jsonb not null check (jsonb_typeof(card_data)='object'), generated_at timestamptz not null default now());
create index on skillswipe.skill_claims(skill_domain_id,active,sort_order); create index on skillswipe.invitations(profile_id,status); create index on skillswipe.skill_signals(profile_id,skill_claim_id); create index on skillswipe.claim_confidence_snapshots(profile_id,public_status,calculated_at desc);

alter table skillswipe.profiles enable row level security; alter table skillswipe.skill_domains enable row level security; alter table skillswipe.skill_claims enable row level security; alter table skillswipe.invitations enable row level security; alter table skillswipe.reviewers enable row level security; alter table skillswipe.skill_signals enable row level security; alter table skillswipe.claim_confidence_snapshots enable row level security; alter table skillswipe.profile_share_cards enable row level security;
create policy owner_profiles_all on skillswipe.profiles for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy public_profiles_read on skillswipe.profiles for select to anon,authenticated using (visibility in ('public','link_only'));
create policy taxonomy_domains_read on skillswipe.skill_domains for select to anon,authenticated using (true); create policy taxonomy_claims_read on skillswipe.skill_claims for select to anon,authenticated using (active);
create policy owner_invitations_all on skillswipe.invitations for all to authenticated using (exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.user_id=(select auth.uid()))) with check (exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.user_id=(select auth.uid())));
create policy owner_reviewers_read on skillswipe.reviewers for select to authenticated using (exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.user_id=(select auth.uid())));
create policy owner_signals_read on skillswipe.skill_signals for select to authenticated using (exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.user_id=(select auth.uid())));
create policy public_approved_signals_read on skillswipe.skill_signals for select to anon,authenticated using (show_evidence_publicly and owner_approved_publicly and exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.visibility in ('public','link_only')) and exists(select 1 from skillswipe.claim_confidence_snapshots c where c.profile_id=skill_signals.profile_id and c.skill_claim_id=skill_signals.skill_claim_id and c.public_status='validated'));
create policy owner_signals_update on skillswipe.skill_signals for update to authenticated using (exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.user_id=(select auth.uid()))) with check (exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.user_id=(select auth.uid())));
create policy owner_snapshots_read on skillswipe.claim_confidence_snapshots for select to authenticated using (exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.user_id=(select auth.uid())));
create policy public_validated_snapshots_read on skillswipe.claim_confidence_snapshots for select to anon,authenticated using (public_status='validated' and exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.visibility in ('public','link_only')));
create policy owner_share_cards_all on skillswipe.profile_share_cards for all to authenticated using (exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.user_id=(select auth.uid()))) with check (exists(select 1 from skillswipe.profiles p where p.id=profile_id and p.user_id=(select auth.uid())));

create view skillswipe.public_validated_claims with (security_invoker=true) as select p.profile_slug,p.full_name,p.headline,p.avatar_url,p.company_name,d.name domain,c.claim_text,s.confidence_score,s.contributor_count,s.independent_relationship_count,s.recognised_count,s.seen_in_practice_count,s.would_call_count,s.calculated_at from skillswipe.profiles p join lateral (select * from skillswipe.claim_confidence_snapshots z where z.profile_id=p.id and z.public_status='validated' order by calculated_at desc limit 100) s on true join skillswipe.skill_claims c on c.id=s.skill_claim_id join skillswipe.skill_domains d on d.id=c.skill_domain_id where p.visibility in ('public','link_only');
create view skillswipe.public_approved_evidence with (security_invoker=true) as select p.profile_slug,s.skill_claim_id,s.evidence_text,s.relationship_type,s.created_at from skillswipe.skill_signals s join skillswipe.profiles p on p.id=s.profile_id where p.visibility in ('public','link_only') and s.show_evidence_publicly and s.owner_approved_publicly and s.evidence_text is not null;

create or replace function skillswipe.map_evidence_level(p_response skillswipe.response_type,p_relationship skillswipe.relationship_type) returns skillswipe.evidence_level language sql immutable set search_path='' as $$ select case when p_response='would_call' then 'does'::skillswipe.evidence_level when p_response='seen_in_practice' and p_relationship in ('client','direct_manager','direct_project_peer') then 'does'::skillswipe.evidence_level when p_response='seen_in_practice' then 'shows_how'::skillswipe.evidence_level else 'knows'::skillswipe.evidence_level end $$;

create or replace function skillswipe.review_invitation(p_token text) returns jsonb language plpgsql security definer set search_path='' as $$ declare inv skillswipe.invitations; result jsonb; begin select * into inv from skillswipe.invitations where token_hash=encode(digest(p_token,'sha256'),'hex') and expires_at>now() and status in ('created','opened'); if inv.id is null then raise exception 'Invalid or expired invitation'; end if; update skillswipe.invitations set status='opened' where id=inv.id and status='created'; select jsonb_build_object('invitation_id',inv.id,'profile',(select jsonb_build_object('first_name',split_part(full_name,' ',1),'full_name',full_name,'headline',headline,'avatar_url',avatar_url) from skillswipe.profiles where id=inv.profile_id),'claims',(select jsonb_agg(jsonb_build_object('id',c.id,'domain',d.name,'claim_text',c.claim_text,'context_tags',c.context_tags,'behavioural_chips',c.behavioural_chips) order by d.sort_order,c.sort_order) from skillswipe.skill_claims c join skillswipe.skill_domains d on d.id=c.skill_domain_id where c.active)) into result; return result; end $$;
revoke all on function skillswipe.review_invitation(text) from public; grant execute on function skillswipe.review_invitation(text) to anon,authenticated;

create or replace function skillswipe.submit_review_signal(p_token text,p_relationship skillswipe.relationship_type,p_response skillswipe.response_type,p_claim_id uuid,p_behaviours jsonb default '[]',p_evidence_text text default null,p_quote_consent boolean default false,p_consent_to_store boolean default false) returns uuid language plpgsql security definer set search_path='' as $$ declare inv skillswipe.invitations; rev_id uuid; signal_id uuid; begin if not p_consent_to_store then raise exception 'Consent is required'; end if; if p_evidence_text is not null and char_length(p_evidence_text)>180 then raise exception 'Evidence exceeds 180 characters'; end if; select * into inv from skillswipe.invitations where token_hash=encode(digest(p_token,'sha256'),'hex') and expires_at>now() and status in ('created','opened'); if inv.id is null then raise exception 'Invalid or expired invitation'; end if; if not exists(select 1 from skillswipe.skill_claims where id=p_claim_id and active) then raise exception 'Invalid claim'; end if; insert into skillswipe.reviewers(invitation_id,profile_id,relationship_type,consent_to_store) values(inv.id,inv.profile_id,p_relationship,true) returning id into rev_id; insert into skillswipe.skill_signals(profile_id,reviewer_id,skill_claim_id,response_type,relationship_type,selected_behaviours,evidence_text,show_evidence_publicly,evidence_level) values(inv.profile_id,rev_id,p_claim_id,p_response,p_relationship,coalesce(p_behaviours,'[]'),case when p_response in ('recognised','seen_in_practice','would_call') then nullif(trim(p_evidence_text),'') else null end,case when p_response in ('recognised','seen_in_practice','would_call') then p_quote_consent else false end,skillswipe.map_evidence_level(p_response,p_relationship)) returning id into signal_id; return signal_id; end $$;
revoke all on function skillswipe.submit_review_signal(text,skillswipe.relationship_type,skillswipe.response_type,uuid,jsonb,text,boolean,boolean) from public; grant execute on function skillswipe.submit_review_signal(text,skillswipe.relationship_type,skillswipe.response_type,uuid,jsonb,text,boolean,boolean) to anon,authenticated;

grant usage on schema skillswipe to anon,authenticated; grant select on skillswipe.skill_domains,skillswipe.skill_claims,skillswipe.profiles,skillswipe.skill_signals,skillswipe.claim_confidence_snapshots,skillswipe.public_validated_claims,skillswipe.public_approved_evidence to anon,authenticated; grant select,insert,update,delete on all tables in schema skillswipe to authenticated;
